global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alert_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['notrus-prom-alertmanager.railway.internal:9093']

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'notrus-api'
    static_configs:
      - targets: ['api.notrus.ai:443']
    metrics_path: '/metrics'
    scrape_interval: 15s
    scrape_timeout: 5s
    scheme: https
    honor_labels: true

  - job_name: 'notrus-web'
    static_configs:
      - targets: ['dashboard.notrus.ai:443']
    metrics_path: '/'
    scrape_interval: 15s
    scrape_timeout: 5s
    scheme: https
    honor_labels: true

  - job_name: 'notrus-webhook'
    static_configs:
      - targets: ['api.notrus.ai:443']
    metrics_path: '/webhook/health'
    scrape_interval: 15s
    scrape_timeout: 5s
    scheme: https
    honor_labels: true
